train_rounds: 100
early_stop_rounds: 90
verbose_eval: 50
cat_feats:
hparams:
# see https://lightgbm.readthedocs.io/en/latest/Parameters.html
    boosting: gbdt
    objective: binary  # 'binary', 'regression', 'regression_l1', ...
    tree_learner: serial
    metric: ['binary_error', 'binary_logloss', 'auc']
    num_threads: 0
    learning_rate: 0.02
    max_depth: -1
    num_leaves: 31
    min_data_in_leaf: 20
    scale_pos_weight: 1
    bagging_fraction: 0.8
    colsample_bytree: 1.0
    max_bin: 255
    min_child_weight: 0.001
    lambda_l2: 1.0
    lambda_l1: 0.0
    metric_freq: 1
    verbosity: -1
